language: csharp
solution: AgariDotNet.sln
dotnet: 3.1.101
os: linux
addons:
  ssh_known_hosts: 84.22.102.178
script:
- dotnet restore
- dotnet test
deploy:
- provider: script
  script: bash deploy/deploy.sh
  on:
    branch: master
before_deploy:
- openssl aes-256-cbc -K $encrypted_6759c9d09779_key -iv $encrypted_6759c9d09779_iv
  -in deploy/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
